extends Node

var input_actions = {
	"MoveUp": "Move up",
	"MoveLeft": "Move left",
	"MoveDown": "Move down",
	"MoveRight": "Move right",
	"Jump" : "Jump",
	"Dash" : "Dash",
	"Climb" : "Climb",
	"Interact" : "Interact",
	
	"ShipForward" : "Ship forward",
	"ShipBack" : "Ship backward",
	"ShipSteerRight" : "Ship steer right",
	"ShipSteerLeft" : "Ship steer left",
	"ShipBoost" : "Ship boost",
	
	"Pause" : "Pause",
	"UIConfirm" : "UI confirm",
	"UIBack" : "UI back",
	
}

var key_icons = {
	"Escape" : 0,
	"F1" : 1,
	"F2" : 2,
	"F3" : 3,
	"F4" : 4,
	"F5" : 5,
	"F6" : 6,
	"F7" : 7,
	"F8" : 8,
	"F9" : 9,
	"F10" : 10,
	"F11" : 11,
	"F12" : 12,
	"AsciiCircum" : 13, 
	"1" : 14,
	"2" : 15,
	"3" : 16,
	"4" : 17,
	"5" : 18,
	"6" : 19,
	"7" : 20,
	"8" : 21,
	"9" : 22,
	"0" : 23,
	"NumberSign" : 24,
	"Equal" : 25,
	"Q" : 26,
	"W" : 27,
	"E" : 28,
	"R" : 29,
	"T" : 30,
	"Y" : 31,
	"U" : 32,
	"I" : 33,
	"O" : 34,
	"P" : 35,
	"BracketLeft" : 36,
	"BracketRight" : 37,
	"Backslash" : 38,
	"A" : 39,
	"S" : 40,
	"D" : 41,
	"F" : 42,
	"G" : 43,
	"H" : 44,
	"J" : 45,
	"K" : 46,
	"L" : 47,
	"Semicolon" : 48,
	"Apostrophe" : 49,
	"Z" : 50,
	"X" : 51,
	"C" : 52,
	"V" : 53,
	"B" : 54,
	"N" : 55,
	"M" : 56,
	"Comma" : 57,
	"Period" : 58,
	"Slash" : 59,
	"Left" : 60,
	"Down" : 61,
	"Up" : 62,
	"Right" : 63
};

var wide_key_icons = {
	"Tab" : 0,
	"CapsLock" : 1,
	"Shift" : 2,
	"Ctrl" : 3,
	"Alt" : 4,
	"Backspace" : 5,
	"Enter" : 6
}

var input_actions_controller = {
	"MoveUpC": "Move up",
	"MoveLeftC": "Move left",
	"MoveDownC": "Move down",
	"MoveRightC": "Move right",
	"JumpC" : "Jump",
	"DashC" : "Dash",
	"ClimbC" : "Climb",
	"InteractC" : "Interact",
	
	"ShipForwardC" : "Ship forward",
	"ShipBackC" : "Ship backward",
	"ShipSteerRightC" : "Ship steer right",
	"ShipSteerLeftC" : "Ship steer left",
	"ShipBoostC" : "Ship boost",
	
	"PauseC" : "Pause",
	"UIConfirmC" : "UI confirm",
	"UIBackC" : "UI back",
	
}

var button_icons = {
	"Joypad Button 2 (Left Action, Sony Square, Xbox X, Nintendo Y)" : 0,
	"Joypad Button 0 (Bottom Action, Sony Cross, Xbox A, Nintendo B)" : 1,
	"Joypad Button 3 (Top Action, Sony Triangle, Xbox Y, Nintendo X)" : 2,
	"Joypad Button 1 (Right Action, Sony Circle, Xbox B, Nintendo A)" : 3,
	"Joypad Button 4 (Back, Sony Select, Xbox Back, Nintendo -)" : 4,
	"Joypad Button 6 (Start, Xbox Menu, Nintendo +)" : 5,
	"Joypad Button 11 (D-pad Up)" : 6,
	"Joypad Button 12 (D-pad Down)" : 7,
	"Joypad Button 13 (D-pad Left)" : 8,
	"Joypad Button 14 (D-pad Right)" : 9,
	"Joypad Motion on Axis 4 (Joystick 2 X-Axis, Left Trigger, Sony L2, Xbox LT) with Value 1.00" : 10, 
	"Joypad Motion on Axis 5 (Joystick 2 Y-Axis, Right Trigger, Sony R2, Xbox RT) with Value 1.00" : 11,
	"Joypad Button 9 (Left Shoulder, Sony L1, Xbox LB)" : 12,
	"Joypad Button 10 (Right Shoulder, Sony R1, Xbox RB)" : 13
};

var stick_icons = {
	"Joypad Motion on Axis 1 (Left Stick Y-Axis, Joystick 0 Y-Axis) with Value -1.00" : 0,
	"Joypad Motion on Axis 0 (Left Stick X-Axis, Joystick 0 X-Axis) with Value -1.00" : 1,
	"Joypad Motion on Axis 1 (Left Stick Y-Axis, Joystick 0 Y-Axis) with Value 1.00" : 3,
	"Joypad Motion on Axis 0 (Left Stick X-Axis, Joystick 0 X-Axis) with Value 1.00" : 2,
	"Joypad Motion on Axis 3 (Right Stick Y-Axis, Joystick 1 Y-Axis) with Value -1.00" : 5,
	"Joypad Motion on Axis 2 (Right Stick X-Axis, Joystick 1 X-Axis) with Value -1.00" : 6,
	"Joypad Motion on Axis 3 (Right Stick Y-Axis, Joystick 1 Y-Axis) with Value 1.00" : 7,
	"Joypad Motion on Axis 2 (Right Stick X-Axis, Joystick 1 X-Axis) with Value 1.00" : 8,
}
